name: Weekly Update

permissions:
  contents: write

on:
  workflow_dispatch:
   
jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
      - name: Check Github CLI presence
        run: gh --version

      - name: Compute Start of the month
        id: date
        run: |
          echo "monthStart=$(date -u +'%Y-%m-01T00:00:00Z')" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v7
     
      - name: Fetch Contributions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api graphql \
            -F login="${{github.repository_owner}}"
            -F from="${{steps.date.outputs.monthStart}}"
            -f query='
            query($login: String!) {
              user(login: $login) {
                contributionsCollection(from: $from) {
                  totalCommitContributions
                  totalIssueContributions
                  totalPullRequestContributions
                  totalRepositoryContributions
                  contributionCalendar {
                    weeks {
                      contributionDays {
                        contributionCount
                        date
                        color
                      } 
                    }
                  }
                }
              }
            }' > contributions.json
      
      - name: Upload contribution data
        uses: actions/upload-artifact@v7
        with:
          name: contributions-data
          path: contributions.json

      # - name: Generate SVG
      #   run: python generate.py contributions.json

      # - name: Commit and push
      #   run: |
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      #     git add -A
      #     git commit -m "[Workflow] Initialize repository as ${{ steps.name.outputs.safe }}"
      #     git push