name: weeklyUpdates

permissions:
  contents: write

on:
  workflow_dispatch:
   
jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
      - name: Check Github CLI presence
        run: gh --version

      - name: Compute Dates
        id: date
        run: |
          echo "monthStart=$(date -u +'%Y-%m-01T00:00:00Z')" >> "$GITHUB_OUTPUT"
          echo "monthEnd=$(date -u -d "$(date -u +'%Y-%m-01') +1 month -1 day" +'%Y-%m-%dT23:59:59Z')" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v7
     
      - name: Fetch Contributions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api graphql \
            -F login="Motisma479" \
            -F from="2026-07-01T00:00:00Z" \
            -F to="2026-07-31T23:59:59Z" \
            -F gitFrom="2026-07-01T00:00:00Z" \
            -F gitTo="2026-07-31T23:59:59Z" \
            -f query='
            query($login: String!, $from: DateTime!, $to: DateTime!, $gitFrom: GitTimestamp!, $gitTo: GitTimestamp!) {
              user(login: $login) {
                contributionsCollection(from: $from, to: $to) {
                  totalCommitContributions
                  totalIssueContributions
                  totalPullRequestContributions
                  totalPullRequestReviewContributions
                  totalRepositoriesWithContributedCommits
                  totalRepositoriesWithContributedIssues
                  totalRepositoriesWithContributedPullRequestReviews 
                  totalRepositoriesWithContributedPullRequests 
                  totalRepositoryContributions 
                  contributionCalendar {
                    weeks {
                      contributionDays {
                        contributionCount
                        date
                        contributionLevel
                      } 
                    }
                  }
                }
                repositories(first: 100, orderBy: {
                    field: UPDATED_AT
                    direction: DESC
                  }
                ) {
                  nodes {
                    name 
                    defaultBranchRef {
                      target {
                        ... on Commit {
                          history(since: $gitFrom, until: $gitTo) {
                            totalCount
                          }
                        }
                      }
                    }
                  }
                }
              }
            }' > contributions.json
      
      - name: Upload contribution data
        uses: actions/upload-artifact@v7
        with:
          name: contributions-data
          path: contributions.json

      # - name: Generate SVG
      #   run: python generate.py contributions.json

      # - name: Commit and push
      #   run: |
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      #     git add -A
      #     git commit -m "[Workflow] Initialize repository as ${{ steps.name.outputs.safe }}"
      #     git push